Drivers:
   OpcUa:
    - Id: "opcua_driver"
      Enabled: true
      LogLevel: INFO
      EndpointUrl: "opc.tcp://192.168.1.4:62541"
      UpdateEndpointUrl: true
      SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
Loggers:
  Neo4j:
    - Id: "neo4j_logger"
      Enabled: true
      Url: bolt://linux0.rocworks.local:7687
      Username: "neo4j"
      Password: "manager123$"
      Schemas:
        - System: opcua_driver
      Logging:
        - Topic: opc/opcua_driver/path/Objects/#