Drivers:
  Mqtt:
  - Id: "MqttClient1"
    Host: xxxxxxxxxxxxxxxxxx.s1.eu.hivemq.cloud
    Port: 8883    
    Ssl: true
    Format: SparkplugB    
    Username: "vogler"
    Password: "xxxxxxxxxxxxxxxx"    

Loggers:
  InfluxDB:
    - Id: InfluxLogger1
      Enabled: true 
      Url: http://nuc1b.rocworks.local:8086
      Database: test
      WriteParameters:
        QueueSize: 20000
        BlockSize: 10000
      Logging:
        - Topic: mqtt/MqttClient1/path/Austria/Sparkplug/#        