# OPC UA Aggregation to Frankenstein OPC UA Server

Drivers:
  OpcUa:
    - Id: "demo1"
      Enabled: true
      LogLevel: INFO
      EndpointUrl: "opc.tcp://192.168.1.4:62540/server"
      UpdateEndpointUrl: true
      SecurityPolicy: None

    - Id: "demo2"
      Enabled: true
      LogLevel: INFO
      WriteSchemaToFile: false
      EndpointUrl: "opc.tcp://192.168.1.4:62541"
      UpdateEndpointUrl: true
      SecurityPolicy: None

    - Id: "s7"
      Enabled: true
      LogLevel: INFO
      EndpointUrl: "opc.tcp://192.168.1.99:4840"
      UpdateEndpointUrl: true
      SecurityPolicy: None

Servers:
  OpcUa:
    - Port: 4841
      Enabled: true
      LogLevel: INFO
      Topics:
        - Topic: opc/demo1/path/Objects/Dynamic/#
        - Topic: opc/demo2/path/Objects/Demo/Simulation/#
        - Topic: opc/s7/path/Objects/PLC_1/DataBlocksGlobal/DB5/#
