Servers:
  OpcUa:
    - Id: opc
      Topics:
        - Topic: mqtt/spb/path/spBv1.0/#

Drivers:
  Mqtt:
    - Id: spb
      LogLevel: FINE
      Host: 192.168.1.4
      Port: 1883
      Format: SparkplugB

Loggers:
  Mqtt:
    - Id: test
      LogLevel: FINE
      Host: 192.168.1.4
      Port: 1883
      Format: Raw
      Logging:
        - Topic: mqtt/spb/path/spBv1.0/#
