Drivers:
  OpcUa:
    - Id: "home1"
      Enabled: true
      LogLevel: INFO
      EndpointUrl: "opc.tcp://scada:4841/server"
      UpdateEndpointUrl: true
      SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None

Loggers:
  Jdbc:   
    - Id: risingwave1
      Enabled: true
      Url: jdbc:postgresql://linux0:4566/dev
      SqlDbType: RisingWave
      Username: root
      Password: ""
      Logging:
        - Topic: opc/home1/path/ns=2;s=85\/Mqtt\/home/#