# MQTT and GraphQL Server

Drivers:
  OpcUa:
    - Id: "demo1"
      Enabled: true
      LogLevel: INFO
      EndpointUrl: "opc.tcp://192.168.1.4:62540/server"
      UpdateEndpointUrl: true
      SecurityPolicy: None

    - Id: "demo2"
      Enabled: true
      LogLevel: INFO
      WriteSchemaToFile: false
      EndpointUrl: "opc.tcp://192.168.1.4:62541"
      UpdateEndpointUrl: true
      SecurityPolicy: None

    - Id: "s7"
      Enabled: true
      LogLevel: INFO
      EndpointUrl: "opc.tcp://192.168.1.99:4840"
      UpdateEndpointUrl: true
      SecurityPolicy: None

  Mqtt:
    - Id: "home"
      Enabled: true
      LogLevel: INFO
      Host: 192.168.1.4
      Port: 1883
      Format: Json
      CustomJson:
        Value: "Value"
        TimestampMs: "TimeMS"
        TimestampIso: "TimeISO"

Servers:
  GraphQL:
    - Port: 4000
      LogLevel: INFO
      GraphiQL: true

  Mqtt:
    - Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO
