Servers:
  Mqtt:
    - Port: 1883
      Host: 0.0.0.0
      LogLevel: INFO # ALL | INFO

Drivers:
  Mqtt:
    - Id: "home"
      Enabled: true
      LogLevel: INFO
      Host: scada
      Port: 1883
      Format: Json
      CustomJson:
        Value: "Value"
        TimestampMs: "TimeMS"
        TimestampIso: "TimeISO"

  OpcUa:
    - Id: "demo1"
      Enabled: true
      LogLevel: INFO
      EndpointUrl: "opc.tcp://192.168.1.4:62540/server"
      UpdateEndpointUrl: true
      SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
      KeepAliveFailuresAllowed: 0
      SubscriptionSamplingInterval: 0.0

    - Id: "demo2"
      Enabled: true
      LogLevel: INFO
      EndpointUrl: "opc.tcp://192.168.1.4:62541"
      UpdateEndpointUrl: true
      SecurityPolicyUri: http://opcfoundation.org/UA/SecurityPolicy#None
      KeepAliveFailuresAllowed: 0
      SubscriptionSamplingInterval: 0.0

Loggers:
  OpenSearch:
    - Id: "search1"
      Enabled: true
      LogLevel: INFO
      Host: linux0
      Port: 9200
      Index: gateway
      Logging:
        - Topic: mqtt/home/path/Original/#
        - Topic: opc/demo1/path/Objects/Variables/#
        - Topic: opc/demo2/path/Objects/Demo/SimulationMass/#

