Drivers:
  Mqtt:
    - Id: "home"
      Enabled: true
      LogLevel: INFO
      Host: 192.168.1.4
      Port: 1883
      ClientId: frankenstein-driver
      Format: Json
      CustomJson:
        Value: "Value"
        TimestampMs: "TimeMS"
        TimestampIso: "TimeISO"

Loggers:
  Jdbc:
    - Id: risingwave
      Enabled: true
      Url: jdbc:postgresql://nuc1:4566/dev
      Username: root
      Password: ""
      Logging:
        - Topic: mqtt/home/path/Original/#


